name: release-chart
on:
  push:
    tags: 'chart.*'
    # branches:
    #  - test-auto-publish

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          charts_dir: chart
          charts_url: https://blazhovsky.github.io/chart-publish-test/
          owner: blazhovsky
          repository: chart-publish-test
          branch: gh-pages
          target_dir: charts
          commit_username: blazhovsky
          commit_email: blagoja.stojkoski@gmail.com