name: release-chart
on:
  push:
    # tags: 'chart.*'
    branches:
     - test-publish-action-dave
#test
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          repository: blazhovsky/ckan-helm
          ref: refs/heads/test-publish-action-dave
          # path: ./
          # token: ${{ secrets.HELM_PUBLISH }}
      
      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          repository: blazhovsky/chart-publish-test
          ref: refs/heads/master
          path: charts-to-publish
          token: ${{ secrets.HELM_PUBLISH }}
      
      - name: Publish the Helm chart
        id: publish-chart
        uses: moikot/chart-publish-action@v1
        with:
          chart: "./"
          charts_dir: "./"
          charts_url: "https://blazhovsky.github.io/chart-publish-test"

      
      - name: Commit and push helm-charts
        uses: EndBug/add-and-commit@v6
        with:
          author_name: Blagoja Stojkoski
          author_email: email@email.com
          branch: gh-pages
          cwd: charts-to-publish
          message: "Commit chart ${{ steps.publish-chart.outputs.chart }}"